### ISSUE TITLE
PDF Service

### ISSUE THREAD

**Issue by nataliesiejczuk** [openstax/baked-pdf#10]
**Description** 
As a Content Manager I want PDF generation to be part of post-publication processing so that I can easily provide content in both Webview and PDF.

**Technical Notes**
Need a python developer to assist with this.
Implement post-publication webhooks
As part of the post-publication processing, trigger predefined webhooks to external services (i.e. pdf generation).
Verify the post-publication proc is available and configured within in cnx-deploy
Implement procedure in the post-publication process that calls a predefined/configured set of urls (webhook endpoints)
Role @trellouser --- olp: 2,9,12

Analysis: Design API for service (write user stories)
Aside: PZS thinks it would be nice to have a public page that shows build status (like travis-ci.org)
Progress? (pipe console messages?)
Success?
Errors?
Look into using the same interface (state and errors) cnx-publishing uses
Role @trellouser --- olp: 6,6,9

- AMQP to talk between BakedPDF and publishing(?)
- download HTML and images (to create the PDF)
- URL for hosting the resulting PDF
- Need a python developer to assist with this.

Implement PDF generation web service
Create a web service that generates PDFs for requested content.
Implement web service that utilizes the PDF building process implemented in previous tasks
Use Celery to allow for async builds of PDFs and persistence of requests
Role @trellouser --- olp: 9,9,9

 Configure PDF generation in cnx-deploy
Configure the web service and ancillary procs necessary to run the service as part of a deploy in cnx-deploy
Set up Flower for inspection of Celery tasks
Role @trellouser --- olp: 12,12,12

**Acceptance Criteria**
- When a user publishes any module or collection, the processes triggered include the PDF generation process for all books with that module, unless the book is locked for PDF generation. 
- After a book is published, the PDF is available on the web

**Link to Story in Epic Document**
https://docs.google.com/document/d/1Pm9X6zGH2KoZFtuZ7-fW04-MVGdzcwmFQ_a1Fs5GxQM/edit#heading=h.letpes6w68v1

**Comment by aiwenar** [comment]
We need to decide on:

- [ ] How to listen for new jobs
- [ ] Where/how to get content for baking/typesetting
  - [ ] content
  - [ ] PDF style
  - [ ] recipes
  - [ ] media files
- [ ] Where/how to store generated PDFs

**Comment by kathi-fletcher** [comment]
This story has been updated in the Epic -- Please review. And also we do need a technical brief for this before development begins.

https://docs.google.com/document/d/1Pm9X6zGH2KoZFtuZ7-fW04-MVGdzcwmFQ_a1Fs5GxQM/edit#heading=h.letpes6w68v1
