### ISSUE TITLE
Write a technical brief for Baked-PDF CLI

### ISSUE THREAD

**Issue by brittweinstein** [openstax/baked-pdf#34]
Here is Kevin's draft: https://docs.google.com/document/d/1OS09KhgjmVJOkI6O5Rvb1w7xSRFOfWuWSuIPlpG6Cnk/edit# 

This includes making decisions surrounding technical architecture.

**Comment by philschatz** [comment]
Also, the epic doc has updated stories on communication between the BakedPDF service and publishing: https://docs.google.com/document/d/1Pm9X6zGH2KoZFtuZ7-fW04-MVGdzcwmFQ_a1Fs5GxQM/edit

Also, here are more annotated notes about the architecture (from Aug '18): https://docs.google.com/document/d/1UNziwpIJk2yyH7nn70jNEPk7kBOVBDnTwpA7d0LOnyQ/edit

**Comment by openstaxalina** [comment]
Adding release label/epic for tracking purposes, not because this must be "code-frozen" next sprint.

**Comment by Bkblodget** [comment]
CLI techinical brief completed (10 points)

Pipeline technical brief to be finished in Q1 (11 points)

**Comment by brittweinstein** [comment]
@Bkblodget does a separate issue exist for the remaining work? Should we break this up?
