### ISSUE TITLE
CLI - Transforming module CNXML to module HTML

### ISSUE THREAD

**Issue by edwoodward** [openstax/baked-pdf#40]
Convert downloaded CNXML to module HTML. The code mentioned below may need to be modified to not access the database since all of the needed files will be local for the CLI user.

We have a trigger called add_module_file for when a file is added to the database (a new entry in the module_files table):

https://github.com/Connexions/cnx-db/blob/ecd8024579f6623faa9143b35c5c688e1fbbec13/cnxdb/archive-sql/schema/triggers.sql#L250

This calls cnxarchive.database.add_module_file:

https://github.com/Connexions/cnx-archive/blob/431084d7941038a8aaa3c37fadd82d6647add752/cnxarchive/database.py#L700

The part we care about is transforming index.cnxml to index.cnxml.html, the functions are cnxdb.triggers.transforms.converters.cnxml_to_full_html:

https://github.com/Connexions/cnx-db/blob/ecd8024579f6623faa9143b35c5c688e1fbbec13/cnxdb/triggers/transforms/converters.py#L107

and cnxdb.triggers.transforms.resolvers.CnxmlToHtmlReferenceResolver (may not be necessary):

https://github.com/Connexions/cnx-db/blob/ecd8024579f6623faa9143b35c5c688e1fbbec13/cnxdb/triggers/transforms/resolvers.py#L328

cnxml_to_full_html uses rhaptos.cnxmlutils to change CNXML to HTML by XSLT.

See [Baked PDF Technical Brief](https://docs.google.com/document/d/12OOzczQx-AJKN3C2pDgbs9I1rQ8XmUchcET5k0rCGH4/edit#heading=h.rdrp96p2bs5x)

**Comment by Bkblodget** [comment]
Sizing estimate is under the assumption that we are not changing links within content (intermodule links etc)
