### ISSUE TITLE
CLI - Create command line interface for all the components.

### ISSUE THREAD

**Issue by edwoodward** [openstax/baked-pdf#44]
**The command line interface should have commands for the following:**

- Run all steps and generate a PDF using Baked HTML
- Run each of these separately and in combination
- Download a Collection
- Convert CNXML to HTML
- Convert Math to SVG
- Generate single HTML file
- Bake HTML
- Generate PDF

**Proposed Commands:**

The CLI will be a part of Neb, so the commands will be a part of the Neb tool.

- Run all commands and generate a PDF: $ neb pdf...
- Fetch content: $ neb get …
- Transform content: $ neb cnxml-to-html …
- Convert Math: $ neb mathify …
- Generate single HTML file: $ neb assemble …
- Bake HTML: $ neb bake …
- Generate PDF $ neb pdf …

See [Baked PDF Technical Brief](https://docs.google.com/document/d/12OOzczQx-AJKN3C2pDgbs9I1rQ8XmUchcET5k0rCGH4/edit#heading=h.rdrp96p2bs5x)

**Test Plan**

Use tool as outlined in the user documentation

**Acceptance Criteria**

Users can run the commands outlined above with these results

neb cnxml-to-html outputs index.cnxml.html files next to every index.cnxml file
neb assemble outputs collection.html next to collection.xml
neb mathify outputs collection.mathified.html next to collection.html
neb bake outputs collection.baked.html next to collection.html
neb pdf outputs collection.pdf next collection.baked.html. It can also be used to run the entire PDF generation pipeline.

So after running all of the steps you’ll end up with a directory which looks like this if you have one module m12345 in the collection col12345:

col12345/
col12345/m12345/
col12345/m12345/index.cnxml
col12345/m12345/index.cnxml.html
col12345/collection.xml
col12345/collection.html
col12345/collection.mathified.html
col12345/collection.baked.html
col12345/collection.pdf
col12345/recipe.css

Or if you have a tree-like structured collection titled Algebra with one module Introduction:

Algebra/
Algebra/Introduction/
Algebra/Introduction/index.cnxml
Algebra/Introduction/index.cnxml.html
Algebra/collection.xml
Algebra/collection.html
Algebra/collection.mathified.html
Algebra/collection.baked.html
Algebra/collection.pdf
Algebra/recipe.css

**Comment by Bkblodget** [comment]
This work is getting separated out into individual single task cards.
