### ISSUE TITLE
Valid XHTML

### ISSUE THREAD

**Issue by nataliesiejczuk** [openstax/baked-pdf#5]
**Description**
As a developer I want the output in each step of the publishing pipeline (including exercises) to be XHTML so that I can use it in external pipelines and ideally open in a browser (if it is a fragment in an HTML page).

"Need to futz with various outputters in python" - reedstrm

https://github.com/Connexions/cnx-easybake/issues/50

**Technical Notes**

Some of this has already been coded; see the Trello card for more information.

**Acceptance Criteria** 
* For each output file, the browser maintains the DOM tree
* Each developer-exposed intermediate content form Is HTML-parsable XHTML
  * CNXML->HTML conversion of individual pages
  * raw epub
  * single-page HTML
  * Single-page baked HTML
  * Baked epub
* Each step in the pipeline takes XHTML as input and outputs XHTML
* The XHTML in every step is HTML-parseable (no `<a/>` or `<span/>` or `<div/>` or `<iframe/>` tags)

**Link to Story in Epic Document**
https://docs.google.com/document/d/1Pm9X6zGH2KoZFtuZ7-fW04-MVGdzcwmFQ_a1Fs5GxQM/edit#heading=h.dlocn4fdnf72

**Comment by philschatz** [comment]
There is a version of an XHTML grammar in RNG at https://github.com/Connexions/cnxml/pull/9 which I thinnk we should use. It contains a subset of XHTML that we use for books (and autogenerated documentation)

Also, updates to the CNXML->XHTML conversion to match the XHTML grammar are at https://github.com/Connexions/rhaptos.cnxmlutils/pull/157 (but still need to be tweaked a bit)

**Comment by openstaxalina** [comment]
This is related to https://github.com/Connexions/webview/issues/1666

**Comment by philschatz** [comment]
Another Issue that was brought up is that `<iframe>` are being written as self-closing (`<iframe src="..."/>`, rather than `<iframe src="..."></iframe>` which causes HTML websites to fail.


/cc @TomWoodward

**Comment by philschatz** [comment]
Another aspect to verify is  that the `<math>` tag never looks like `<m:math>`. This breaks MathJax. See `#x-20190109-equations` https://openstax.slack.com/archives/CF9RPK12P/p1547048953003600

<blockquote><img src="https://a.slack-edge.com/436da/marketing/img/meta/favicon-32.png" width="48" align="right"><div><strong><a href="https://openstax.slack.com/archives/CF9RPK12P/p1547048953003600">Slack</a></strong></div></blockquote>

**Comment by brittweinstein** [comment]
@Bkblodget is this issue represented elsewhere?

**Comment by Bkblodget** [comment]
Issue moved to [openstax/cnx #261](https://github.com/openstax/cnx/issues/261) via [**ZenHub**](https://www.zenhub.com/)
