### ISSUE TITLE
Legacy Does Not Enqueue Baked PDFs

### ISSUE THREAD

**Issue by nataliesiejczuk** [openstax/baked-pdf#9]
### Description
As an OpenStax developer, I want to support 2 pipelines so that legacy does not enqueue books that are in the BakedPDF pipeline.

### Technical Notes
This is mostly a legacy change.  At publish time, it would check to see if the print style is a PDF template.  If so, treat this as a locked PDF.

- Add collection style for non-CCAP style
- Don’t do publish time enqueue if that style is set
- In downstream of queue script, detect that style and bail early (in case of manual enqueue)
- We need this in the transitional phase while only some books are in the BakedPDF pipeline. 
- Need a Python dev to assist with this.
- Need to discuss how this can be tested.
- Instead of adding an extra flag, we could use the book name “w/ recipe” to determine which pipeline to use.
- Need to support 3 cases: “CCAP template”; “w/ recipe”; “w/ Baked pdf”
- Legacy can look at the database to determine which of the cases applies ^

### Acceptance Criteria 

- legacy software recognizes that the selected print-style is a recipe and does not build the docbook based pdf
- the newer baked pdf service ignores content that has print-style pointing to docbook template based print-style

### Link to Story in Epic Document
https://docs.google.com/document/d/1Pm9X6zGH2KoZFtuZ7-fW04-MVGdzcwmFQ_a1Fs5GxQM/edit#heading=h.x2m3l3kevbid

**Comment by pumazi** [comment]
acceptance criteria item: legacy software recognizes that the selected print-style is a recipe and does not build the docbook based pdf

**Comment by pumazi** [comment]
tests for this will likely require the tests be written in cnx-automation, because this bridges between services

**Comment by kathi-fletcher** [comment]
This story has been updated in the epic doc and should be a part of BakedPDF technical brief:

https://docs.google.com/document/d/1Pm9X6zGH2KoZFtuZ7-fW04-MVGdzcwmFQ_a1Fs5GxQM/edit#heading=h.x2m3l3kevbid
